services:
  - type: web
    name: tecpoint
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: SMTP_SERVER
        value: smtps.uhserver.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USERNAME
        value: contato@tecpoint.net.br
      - key: SMTP_PASSWORD
        sync: false
    autoDeploy: true
